---
title: Provisioning Telephony
description: This tutorial implements BYOC Cloud solution with a cloud-based carrier 
categories:
- Trunk
- Telephony
steps:
- title: Introduction
  content: |
    This tutorial walks through the steps on how to implement BYOC Cloud in Genesys Cloud using [Purecloud Platform API](/rest/client-libraries/index.html). In order for BYOC Cloud to work with a third-party carrier, the carrier must:
    
    * Be SIP-compliant
    * Support the UDP or TCP trunk transport protocol
    * Have a publicly routable IP address or host name
      * Carriers must fully support Record-Routing as required by RFC 3261 to ensure proper routing of sequential SIP requests.
    
    For more information about carrier requirements, check Genesys Resource Center article [Carrier requirements for BYOC Cloud](https://help.mypurecloud.com/articles/carrier-requirements-byoc-cloud/).
    
    To successfully run the code, a JSON file is needed to provide the necessary input. In this tutorial, the JSON file is titled input-template.json.

- title: JSON Files and Variables
  content: |
    This file is used as substitute to input text box. This is where the user enters all the necessary details. Key value pair has its corresponding description. Please make sure to replace all the value of keys from description to actual data and fill all the required fields to proceed. 
    
    Please refer to [BYOC Cloud public SIP IP addresses](https://help.mypurecloud.com/articles/byoc-cloud-public-sip-ip-addresses/) for instance or Public SIP Addresses.  

- title: Authentication
  content: |
    The app will be authorized using OAuth Client Credentials. Once the validation is successful, it will proceed with the succeeding process.

- title: Check BYOC Feature
  content: |
    Get the list of products available for the org used by calling [getAuthorizationProducts()](/api/rest/client-libraries/javascript/AuthorizationApi.html#organizationproductentitylisting_getauthorizationproducts__) function of Authorization API and check if the org has BYOC capability. If the org is BYOC capable, it will proceed to create location function.  Please take note that only BYOC enabled orgs can proceed.

- title: Create Location
  content: |
    Create a location in Genesys Cloud  by calling [postLocations()](/api/rest/client-libraries/javascript/LocationsApi.html#postLocations) function of the locations API and save the returned location data in a global variable.

- title: Create Site
  content: |
    To create a new site, there are a few pieces of information required before making an API call. First, is the location information which is saved in a global variable from an earlier step. Second, is the default edge group which is found in PureCloud Admin > Telephony > Edge Groups. Third, is the edge software update schedule and in this tutorial set in default schedule window of 2AM to 5AM. Read more about scheduling automatic updates for the edge software [here](https://help.mypurecloud.com/articles/schedule-automatic-updates-edge-software/).

    Get the default edge group by calling [getTelephonyProvidersEdgesSites()](/api/rest/client-libraries/javascript/TelephonyProvidersEdgeApi.html#getTelephonyProvidersEdgesSites) function and look for "PureCloud Voice – AWS". Save the returned data and proceed to creating a new site with [postTelephonyProvidersEdgesSites()](/api/rest/client-libraries/javascript/TelephonyProvidersEdgeApi.html#postTelephonyProvidersEdgesSites) function. Both functions are under telephony providers edge API.

- title: Create Trunk
  content: |
    Create a trunk base setting object from the user input credentials from the JSON file by calling [postTelephonyProvidersEdgesTrunkbasesettings()](/api/rest/client-libraries/javascript/TelephonyProvidersEdgeApi.html#trunkbase_posttelephonyprovidersedgestrunkbasesettings_body_) function of Telephony Providers Edge API. Once the trunk is successfully created, it will proceed to siteOutboundRoutes function. 

- title: Set Outbound Route
  content: |
    Lastly, with the use of telephony providers edge API, get the outbound route created by default when the site was created using [getTelephonyProvidersEdgesSiteOutboundroutes()](/api/rest/client-libraries/javascript/TelephonyProvidersEdgeApi.html#getTelephonyProvidersEdgesSiteOutboundroutes) function, then update the external trunk base value of the trunk created in the previous step by calling [putTelephonyProvidersEdgesSiteOutboundroutes()](/api/rest/client-libraries/javascript/TelephonyProvidersEdgeApi.html#putTelephonyProvidersEdgesEdgegroupEdgetrunkbase) function.

languages:
  nodejs:
    displayName: NodeJS
    steps:
    - file: "nodejs/index.js"
      highlight: "0-331"
    - file: "nodejs/input-template.json"
      highlight: "1-32"
    - file: "nodejs/index.js"
      highlight: "15-25"
    - file: "nodejs/index.js"
      highlight: "27-43"
    - file: "nodejs/index.js"
      highlight: "45-73"
    - file: "nodejs/index.js"
      highlight: "75-137"
    - file: "nodejs/index.js"
      highlight: "139-287"
    - file: "nodejs/index.js"
      highlight: "289-331"
